/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PartnerEarningsRouteImport } from './routes/partner.earnings'
import { Route as PartnerRedeemRouteImport } from './routes/partner.redeem'
import { Route as PartnerTicketsRouteImport } from './routes/partner.tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerEarningsRoute = PartnerEarningsRouteImport.update({
  id: '/partner/earnings',
  path: '/partner/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRedeemRoute = PartnerRedeemRouteImport.update({
  id: '/partner/redeem',
  path: '/partner/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerTicketsRoute = PartnerTicketsRouteImport.update({
  id: '/partner/tickets',
  path: '/partner/tickets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/redeem': typeof PartnerRedeemRoute
  '/partner/tickets': typeof PartnerTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/redeem': typeof PartnerRedeemRoute
  '/partner/tickets': typeof PartnerTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/redeem': typeof PartnerRedeemRoute
  '/partner/tickets': typeof PartnerTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/partner/earnings'
    | '/partner/redeem'
    | '/partner/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/partner/earnings'
    | '/partner/redeem'
    | '/partner/tickets'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/partner/earnings'
    | '/partner/redeem'
    | '/partner/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SignInRoute: typeof SignInRoute
  PartnerEarningsRoute: typeof PartnerEarningsRoute
  PartnerRedeemRoute: typeof PartnerRedeemRoute
  PartnerTicketsRoute: typeof PartnerTicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/earnings': {
      id: '/partner/earnings'
      path: '/partner/earnings'
      fullPath: '/partner/earnings'
      preLoaderRoute: typeof PartnerEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/redeem': {
      id: '/partner/redeem'
      path: '/partner/redeem'
      fullPath: '/partner/redeem'
      preLoaderRoute: typeof PartnerRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/tickets': {
      id: '/partner/tickets'
      path: '/partner/tickets'
      fullPath: '/partner/tickets'
      preLoaderRoute: typeof PartnerTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SignInRoute: SignInRoute,
  PartnerEarningsRoute: PartnerEarningsRoute,
  PartnerRedeemRoute: PartnerRedeemRoute,
  PartnerTicketsRoute: PartnerTicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
